set -g default-shell /bin/zsh

set -g prefix C-Space
unbind C-b
unbind C-a
bind C-Space send-prefix

set -sg escape-time 10
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g detach-on-destroy off

set -g mouse on
set -g mode-keys vi
set -g history-limit 50000
set -g pane-scrollbars off
set -g pane-border-lines spaces

set -g display-time 3000
set -g display-panes-time 4000
set -g status-interval 1
set -g status-left-length 80
set -g status-right-length 100

set -g focus-events on
set -g set-clipboard on

bind '"' split-window -v -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

bind -r m select-pane -t .+
bind -r M select-pane -t .-

bind -r Tab next-window
bind -r C-Tab previous-window

bind -n M-Left previous-window
bind -n M-Right next-window

bind c new-window -c '#{pane_current_path}'
bind , command-prompt -I "#W" { rename-window -- "%%" }
bind . command-prompt -I "#{pane_index}" { swap-pane -s "%%" }
bind x kill-pane
bind X kill-window
bind q confirm-before -p "kill session? (y/n)" kill-session

bind r source-file ~/.tmux.conf \; display "Config reloaded"

bind R command-prompt { rename-session -- "%%" }

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi C-v send -X rectangle-toggle

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @tmux-dotbar-bg 'default'
set -g @tmux-dotbar-fg '#585b70'
set -g @tmux-dotbar-fg-current '#cdd6f4'
set -g @tmux-dotbar-fg-session '#9399b2'
set -g @tmux-dotbar-fg-prefix '#cba6f7'
set -g @tmux-dotbar-left true
set -g @tmux-dotbar-right true
set -g @tmux-dotbar-status-left '#[fg=#9399b2]  #(~/.tmux/scripts/git-status.sh "#{pane_current_path}") '
set -g @tmux-dotbar-status-right '#[fg=#9399b2] #(~/.tmux/scripts/scroll-text.sh "#{b:pane_current_path}" 15)  '

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
set -g @continuum-save-interval '15'

run -b '~/.tmux/plugins/tpm/tpm'
